name: CI

on:
  schedule:
    - cron: '0 7,19 * * *'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
  get-defold-version:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - id: defold
        uses: actionsflow/axios@v1
        with:
          url: http://d.defold.com/stable/info.json    
      - run: echo ${{ steps.defold.outputs.data }}
      - run: sed -nr 's/^\/\/ DEFOLD\. ([A-Za-z]+) version ([0-9\.]+) \(([a-z0-9]+)\)/\2 \3/p' '$GITHUB_WORKSPACE/index.d.ts'
